CODE:
	gcc -g -I/usr/local/include -Wall -o code code.c -lrt -lcornet
	gcc -g -I/usr/local/include -Wall -o cnautotime_server cnautotime_server.c -lrt -lcornet
	LD_LIBRARY_PATH=/usr/local/lib
	export LD_LIBRARY_PATH
